global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

  # Attach these labels to any time series or alerts
  external_labels:
    monitor: 'llm-production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"

# A scrape configuration for running Prometheus on a Kubernetes cluster
scrape_configs:
  # LLM API metrics
  - job_name: 'llm-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['llm-api:8080']
        labels:
          service: 'llm-inference'
          environment: 'production'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          environment: 'production'

  # Node metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'
          environment: 'production'

  # Container metrics
  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'containers'
          environment: 'production'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'monitoring'
          environment: 'production'

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          service: 'monitoring'
          environment: 'production'

  # Nginx metrics via exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx'
          environment: 'production'

  # Blackbox exporter for endpoint probing
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Use the http_2xx module to check for 200 OK responses
    static_configs:
      - targets:
        - https://api.example.com/health  # Health endpoint to probe
        - https://api.example.com/v1/status  # Status endpoint to probe
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's address

# Alert rules
# Place alert rules in /etc/prometheus/rules/*.yml
# Examples include:
# - High error rate
# - Endpoint down
# - High latency
# - High resource usage 